entidad/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),

    #Login y register
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    
    #Animales
    path("animales/", views.animales, name="animales"),
    path("animales/<int:id>", views.animalesById, name="animal"),
    path("animales/nuevo", views.nuevoAnimal, name="nuevo-animal"),
    path("animales/modificar/<int:id>", views.modificarAnimal, name="modificar-animal"),
    path('animales/eliminar/<int:id>', views.elimiarAnimal, name="eliminar-animal"),

    
    #Clientes
    path("clientes/", views.clientes, name="clientes"),
    path('clientes/<int:id>', views.clienteById, name="cliente"),
    path('clientes/nuevo', views.nuevoCliente, name="nuevo-cliente"),
    path('clientes/modificar/<int:id>', views.modificarCliente, name="modificar-cliente"),
    path('clientes/eliminar/<int:id>', views.elimiarCliente, name="eliminar-cliente"),
    
    #Localidades
    path('localidades/nuevo', views.nuevaLocalidad, name="nueva-localidad"),
    path('localidades/', views.localidades, name="localidades"),
    path('localidades/<int:id>', views.localidad, name="localidad"),

    #Enfermedades
    path('enfermedades/nuevo', views.nuevaEnfermedad, name="nueva-enfermedad"),
    path('enfermedades/', views.enfermedades, name="enfermedades"),

    #Consultas
    path('consultas/nuevo', views.nuevaConsulta, name="nueva-consulta"),
    path('consultas/', views.consultas, name="consultas"),
]

prjveterinaria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("entidad.urls"))
]

entidad/models.py
from django.db import models

TIPO_IVA_CHOICES = (
    ("CF", "Consumidor Final"),
    ("EX", "Exento"),
    ("RI", "Responsable Inscripto"),
    ("MT", "Monotributo"),
    ("OT", "Otro")
)

TIPO_RAZAS_CHOICES = (
    ("GD", "Golden"),
    ("LD", "Labrador"),
    ("RD", "Ragdoll"),
    ("SD", "Saint Bernard"),
    ("TD", "Tibetan"),
    ("WD", "Wild"),
    ("OT", "Otro")
)

TIPO_CATEGORIA_CHOICES = (
        ("CN", 'Canino'),
        ("FO", 'Felino'),
        ("OT", 'Otro')
    )

TIPO_ENFERMEDAD_CHOICES = (
    ("L", "Leve"),
    ("M", "Moderada"),
    ("H", "Grave")
)

class Localidad(models.Model):
    nombre = models.CharField("Nombre de la localidad", max_length=60)
    cp = models.CharField("Codigo postal", max_length=10)
    provincia = models.CharField("Provincia", max_length=60)
    
    def __str__(self):
        return self.nombre + " - " + " " + self.cp + " - " + self.provincia


class Persona(models.Model):
    nombre = models.CharField("Nombre cliente", max_length=60)
    apellido = models.CharField("Apellido del cliente", max_length=60)
    edad = models.IntegerField("Edad", null=True, blank=True)
    localidad = models.ForeignKey(Localidad, on_delete=models.PROTECT, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    activo = models.BooleanField(default=True)
    fecha_nac = models.DateField("Fecha de nacimiento", null=True, blank=True)
    tipo_iva = models.CharField("Tipo de IVA", max_length=2, choices=TIPO_IVA_CHOICES, default="CF")

    def __str__(self):
        return self.nombre


class Instructor(models.Model):
    nombre = models.CharField("Nombre del instructor", max_length=60)
    email = models.EmailField("Email del instructor", max_length=60)
    cursos_asignados = models.IntegerField("Cursos asignados")


class Animal(models.Model):
    nombre = models.CharField("Nombre del animal", max_length=60)
    raza = models.CharField("Raza del animal", max_length=2, choices=TIPO_RAZAS_CHOICES, default="OT")
    categoria = models.CharField("Categoria del animal", max_length=2, choices=TIPO_CATEGORIA_CHOICES, default="OT")
    dueno = models.ForeignKey(Persona, on_delete=models.PROTECT)
    activo = models.BooleanField(default=True)

    
    def __str__(self):
        return self.nombre + ", " + self.dueno.nombre

class Enfermedad(models.Model):
    nombre = models.CharField("Nombre de la enfermedad", max_length=60)
    grado = models.CharField("Grado de la enfermedad", max_length=2, choices=TIPO_ENFERMEDAD_CHOICES)

    def __str__(self):
        return self.nombre


class Consulta(models.Model):
    fecha = models.DateField("Fecha de la consulta")
    costo = models.PositiveIntegerField("Costo de la consulta")
    animal = models.ForeignKey(Animal, on_delete=models.PROTECT)
    enfermedad = models.ForeignKey(Enfermedad, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Consulta: {self.animal} - {self.animal.dueno.nombre}"

entidad/forms.py
from django import forms
from django.forms import ModelForm
from entidad.models import Animal, Consulta, Enfermedad, Localidad, Persona
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
    

class DateInput(forms.DateInput):
    input_type = 'date'

class NuevoCliente(ModelForm):
    class Meta:
        model = Persona
        fields = '__all__'
        exclude = ["activo"]
        widgets = {
            "fecha_nac": DateInput(
                attrs={'type': 'date', 'class': 'form-control input'}
            ),
            "nombre": forms.TextInput(
                attrs= {'class': 'form-control input'}
            ),
            "apellido": forms.TextInput(
                attrs= {'class': 'form-control input'}
            ),
            "edad": forms.NumberInput(
                attrs= {'class': 'form-control input'}
            ),
            "localidad": forms.Select(
                attrs= {'class': 'form-control input'}
            ),
            "email": forms.EmailInput(
                attrs= {'class': 'form-control input'}
            ),
            "tipo_iva": forms.Select(
                attrs= {'class': 'form-control input'}
            ),
            
        }

class NuevoAnimal(ModelForm):
    class Meta:
        model = Animal
        fields = '__all__'
        exclude = ["activo"]
        widgets = {
            "nombre": forms.TextInput(
                attrs= {'class': 'form-control input'}
            ),
            "raza": forms.Select(
                attrs= {'class': 'form-control input'}
            ),
            "categoria": forms.Select(
                attrs= {'class': 'form-control input'}
            ),
            "dueno": forms.Select(
                attrs= {'class': 'form-control input'}
            ),
        }


class NuevaLocalidad(ModelForm):
    class Meta:
        model = Localidad
        fields = '__all__'

class NuevaEnfermedad(ModelForm):
    class Meta:
        model = Enfermedad
        fields = '__all__'
        

class NuevaConsulta(ModelForm):
    class Meta:
        model = Consulta
        fields = '__all__'
        widgets = {
            "fecha": DateInput(
                attrs={'type': 'date'}
            ),
        }

entidad/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from .forms import LoginForm, NuevaConsulta, NuevaEnfermedad, NuevaLocalidad, NuevoCliente, NuevoAnimal
from .models import Consulta, Enfermedad, Localidad, Persona, Animal
from .forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import auth
from django.contrib.auth.decorators import login_required


# Create your views here.

def register(request, template_name="entidad/register.html"):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        form.save()
        return redirect('index')
    context = {"form": form}
    return render(request, template_name, context)

def login(request, template_name="entidad/login.html"):
    form = LoginForm()
    if(request.method == "POST"):
        form = LoginForm(request, data=request.POST)

        username = request.POST.get("username")
        password = request.POST.get("password")
        
        user = authenticate(request, username=username, password=password)

        if user is not None:

                auth.login(request, user)

                return redirect("index")
        
        print(username)
    
    context = {"form": form}
    
    return render(request, template_name, context)


def logout(request):
    
    auth.logout(request)
    
    return redirect("login")


@login_required
def index(request, template_name="entidad/index.html"):
    return render(request, template_name)


def animales(request, template_name="entidad/animales.html"):
    animales = Animal.objects.filter(activo=True)
    context = {"animales": animales}
    return render(request, template_name, context)

def animalesById(request,id ,template_name="entidad/animal.html"):
    animalById = Animal.objects.get(id=id)
    if animalById is None:
        raise Http404
        
    context = {"animal": animalById}
    return render(request, template_name, context)

@login_required
def modificarAnimal(request, id, template_name="entidad/modificar-animal.html"):
    animal = Animal.objects.get(id=id)
    
    if request.method == "POST":
        form = NuevoAnimal(request.POST or None, instance=animal)
        if form.is_valid():
            form.save()
            return redirect("animales")
    else:
        form = NuevoAnimal(instance=animal)
    
    context = {"form": form}
    return render(request, template_name, context)

@login_required
def elimiarAnimal(request, id, template_name="entidad/confirmar-eliminacion.html"):
    animal = Animal.objects.get(id=id)
    if request.method == "POST":
        animal.activo = False
        animal.save()
        return redirect("animales")
    context = {"dato": animal.nombre, "cancel_url": "animales"}
    return render(request, template_name, context)

def clientes(request, template_name="entidad/clientes.html"):
    personas = Persona.objects.filter(activo=True)
    context = {"clientes": personas}
    return render(request, template_name, context)

def clienteById(request, id ,template_name="entidad/cliente.html"):
    personaById = Persona.objects.get(id=id)
    if personaById is None:
        raise Http404
    context = {"cliente": personaById}
    return render(request, template_name, context)

@login_required
def modificarCliente(request, id, template_name="entidad/modificar-cliente.html"):
    cliente = Persona.objects.get(id=id)
    
    if request.method == "POST":
        form = NuevoCliente(request.POST or None, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect("clientes")
    else:
        form = NuevoCliente(instance=cliente)
    
    context = {"form": form}
    return render(request, template_name, context)

@login_required
def elimiarCliente(request, id, template_name="entidad/eliminar-cliente.html"):
    cliente = Persona.objects.get(id=id)
    if request.method == "POST":
        cliente.activo = False
        cliente.save()
        return redirect("clientes")
    context = {"form": cliente}
    return render(request, template_name, context)

@login_required
def nuevoCliente(request, template_name="entidad/nuevo-cliente.html"):
    if request.method == "POST":
        form = NuevoCliente(request.POST)
        if form.is_valid():
            form.save()
            return redirect("clientes")
    else:
        form = NuevoCliente()
        
    context = {"form": form}
    
    return render(request, template_name, context)

@login_required
def nuevoAnimal(request, template_name="entidad/nuevo-animal.html"):
    
    if request.method == "POST":
        form = NuevoAnimal(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('animales')
    else:
        form = NuevoAnimal()

    context = {"form": form}

    return render(request, template_name, context)

@login_required
def nuevaLocalidad(request, template_name="entidad/nueva-localidad.html"):
    if request.method == "POST":
        form = NuevaLocalidad(request.POST)
        if form.is_valid():
            form.save(commit=True)
            redirect('localidades')
    else:
        form = NuevaLocalidad()
        
    context = {"form": form}
    
    return render(request, template_name, context)

def localidades(request, template_name="entidad/localidades.html"):
    localidades_list = Localidad.objects.all()
    context = {"localidades": localidades_list}
    return render(request, template_name, context)

def localidad(request, id, template_name="entidad/localidad.html"):
    localidadById = Localidad.objects.get(id=id)
    if localidadById is None:
        raise Http404
        
    context = {"localidad": localidadById}
    return render(request, template_name, context)

@login_required
def nuevaEnfermedad(request, template_name="entidad/nueva-enfermedad.html"):
    if request.method == 'POST':
        form = NuevaEnfermedad(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('enfermedades')
    else:
        form = NuevaEnfermedad()
        
    context = {'form': form}
    
    return render(request, template_name, context)

def enfermedades(request, template_name="entidad/enfermedades.html"):
    enfermedades_list = Enfermedad.objects.all()
    context = {"enfermedades": enfermedades_list}
    return render(request, template_name, context)

@login_required
def nuevaConsulta(request, template_name="entidad/nueva-consulta.html"):
    if request.method == "POST":
        form = NuevaConsulta(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('consultas')
    else:
        form = NuevaConsulta()

    context = {"form": form}

    return render(request, template_name, context)

def consultas(request, template_name="entidad/consultas.html"):
    consultas_list = Consulta.objects.all()
    context = {"consultas": consultas_list}
    return render(request, template_name, context)

templates/entidad/animal.html
{% extends "base.html" %}
{% load static %}


{% block titulo_principal %}
    My Veterinaria | Animal
{% endblock %}

{% block principal%}
    <section class="clientes_container">
        <h3 style="text-align: center;">Animal</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Raza</th>
                    <th>Categoria</th>
                    <th>Dueño</th>
                </tr>
            </thead>
            <tbody>
                <td>{{ animal.nombre }}</td>
                <td>{{ animal.get_raza_display }}</td>
                <td>{{ animal.get_categoria_display }}</td>
                <td>{{ animal.dueno.nombre }}</td>
                
            </tbody>
        </table>
    </section>
{% endblock %}

templates/entidad/animales.html
{% extends "base.html" %}
{% load static %}

{% block titulo_principal %}
    My Veterinaria | Animales
{% endblock titulo_principal %}

<!-- This is the template for the animals section -->

{% block principal %}
  <section class="container"> 
    <h3 style="text-align: center">Animales</h3>
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Raza</th>
            <th>Categoria</th>
            <th>Dueño</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for animal in animales %}
          <tr>
            <td>{{animal.nombre}}</td>
            <td>{{animal.get_raza_display}}</td>
            <td>{{animal.get_categoria_display}}</td>
            <td>{{animal.dueno.nombre}}</td>
            <td>    
              <a href="{% url 'modificar-animal' animal.id %}" class="btn btn-info">Editar</a>
              <a href="{% url 'animal' animal.id %}" class="btn btn-primary">Detalles</a>    
              <a href="{% url 'eliminar-animal' animal.id %}" class="btn btn-danger">Eliminar</a>
          </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
  </section>
{% endblock principal %}

templates/entidad/clientes.html
{% extends "base.html" %}
{% load static %}


{% block titulo_principal %}
    My Veterinaria | Clientes🫏
{% endblock %}

{% block principal%}
    <section class="container">
        <h3 style="text-align: center;">Clientes</h3>
        <table class="table table-hover text-center custom">
                <thead class="thead-light">
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Edad</th>
                        <th>Email</th>
                        <th>Tipo de Iva</th>
                        <th>Localidad</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for persona in clientes  %}
                        <tr class="p-1 align-items-center">
                            <td class="p-1">{{persona.nombre}}</td>
                            <td class="p-1">{{persona.apellido}}</td>
                            <td class="p-1">{{persona.edad}}</td>
                            <td class="p-1">{{persona.email}}</td>
                            <td class="p-1">{{persona.get_tipo_iva_display}}</td>
                            <td class="p-1">{{persona.localidad.nombre}}</td>
                            <td class="d-flex align-items-center p-1">    
                                <a href="{% url 'modificar-cliente' persona.id %}" class="btn btn-primary">Editar</a>
                                
                            </td>
                        </tr>
                    {% endfor %}
                    
                </tbody>
        </table> 
        
    </section>
{% endblock %}

templates/entidad/consultas.html
{% extends "base.html" %}
{% load static %}


{% block titulo_principal %}
    My Veterinaria | Consultas
{% endblock %}

{% block principal%}
    <section class="container">
        <h3 style="text-align: center;">Consultas</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Costo</th>
                    <th>Animal</th>
                    <th>Dueño</th>
                    <th>Enfermedad</th>
                </tr>
            </thead>
            <tbody>
                {% if consultas.count %}
                    {% for consulta in consultas  %}
                        <tr>
                            <td>{{consulta.fecha}}</td>
                            <td>${{consulta.costo}}</td>
                            <td>{{consulta.animal.nombre}}</td>
                            <td>{{consulta.animal.dueno.nombre}}</td>
                            <td>{{consulta.enfermedad.nombre}}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p>No hay consultas registradas aun.</p>
                {% endif %}
                
            </tbody>
        </table>
    </section>
{% endblock %}

templates/entidad/eliminar-animal.html
{% extends "base.html" %}
{% load static %}


{% block titulo_principal %}
    My Veterinaria | Eliminar
{% endblock %}

{% block principal%}
    <section class="container center-text">
        <form method="POST">
            {% csrf_token %}
            <h1>¿Esta seguro que desea eliminar este animal?</h1>
            <h4>Cliente: {{form.nombre}}</h4>
            <button class="btn btn-primary" type="submit">Eliminar</button>
            <a href="{% url 'animales' %}" class="btn btn-primary" type="button">   
                Cancelar
            </a>
        </form>
    </section>
{% endblock %}

templates/entidad/eliminar-cliente.html
{% extends "base.html" %}
{% load static %}


{% block titulo_principal %}
    My Veterinaria | Eliminar
{% endblock %}

{% block principal%}
    <section class="container center-text">
        <form method="POST">
            {% csrf_token %}
            <h1>¿Esta seguro que desea eliminar este cliente?</h1>
            <h4>Cliente: {{form.nombre}} {{form.apellido}}</h4>
            <button class="btn-delete" type="submit">Eliminar</button>
            <a href="{% url 'clientes' %}" class="btn" type="button">   
                Cancelar
            </a>
        </form>
    </section>
{% endblock %}

templates/entidad/enfermedades.html
{% extends "base.html" %}
{% load static %}


{% block titulo_principal %}
    My Veterinaria | Enfermedades😷
{% endblock %}

{% block principal%}
    <section class="container">
        <h3 style="text-align: center;">Enfermedades</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Grado</th>
                </tr>
            </thead>
            <tbody>
                {% if enfermedades.count %}
                    {% for enfermedad in enfermedades  %}
                        <tr>
                            <td>{{enfermedad.nombre}}</td>
                            <td>{{enfermedad.get_grado_display}}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p>No hay consultas registradas aun.</p>
                {% endif %}
                
            </tbody>
        </table>
    </section>
{% endblock %}

templates/entidad/index.html
{% extends "base.html" %}
{% load static %}


{% block titulo_principal %}
    My Veterinaria | Home
{% endblock %}

{% block principal%}
    <section class="container">
        <h1 class="mt-5 text-center">Bienvenido a la pagina de Lomas Veterinaria, que tenga una buena experiencia!</h1>
        <p>Username: {{user.username.capitalize}}</p>
    </section>
{% endblock %}

templates/entidad/localidad.html
{% extends "base.html" %}
{% load static %}


{% block titulo_principal %}
    My Veterinaria | Localidad
{% endblock %}

{% block principal%}
    <section class="clientes_container">
        <h3 style="text-align: center;">Localidad</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Provincia</th>
                    <th>Codigo postal</th>
                </tr>
            </thead>
            <tbody>
                <td>{{ localidad.nombre }}</td>
                <td>{{ localidad.provincia }}</td>
                <td>{{ localidad.cp }}</td>
            </tbody>
        </table>
    </section>
{% endblock %}

templates/entidad/modificar-animal.html
{% extends "base.html" %}
{% load static  %}

{% block titulo_principal %}
    My Veterinaria | Modificar Animal
{% endblock %}


{% block principal %}

<form method="POST" class="">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="button-submit">
        <span class="button__text">Guardar</span>
        <span class="button__icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" viewBox="0 0 24 24" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" stroke="currentColor" height="24" fill="none" class="svg"><line y2="19" y1="5" x2="12" x1="12"></line><line y2="12" y1="12" x2="19" x1="5"></line></svg></span>
     </button>
</form>

{% endblock principal %}

templates/entidad/nueva-consulta.html
{% extends "base.html" %}
{% load static  %}
{% load crispy_forms_tags %}

{% block titulo_principal %}
    My Veterinaria | Nuevo Consulta
{% endblock %}


{% block principal %}

<form method="POST" class="form-group">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="button-submit">
        <span class="button__text">Crear</span>
        <span class="button__icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" viewBox="0 0 24 24" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" stroke="currentColor" height="24" fill="none" class="svg"><line y2="19" y1="5" x2="12" x1="12"></line><line y2="12" y1="12" x2="19" x1="5"></line></svg></span>
    </button>
</form>

{% endblock principal %}

templates/entidad/nueva-enfermedad.html
{% extends "base.html" %}
{% load static  %}

{% block titulo_principal %}
    My Veterinaria | Nuevo Enfermedad😷
{% endblock %}


{% block principal %}

<form method="POST" class="form-group">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="button-submit">
        <span class="button__text">Crear</span>
        <span class="button__icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" viewBox="0 0 24 24" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" stroke="currentColor" height="24" fill="none" class="svg"><line y2="19" y1="5" x2="12" x1="12"></line><line y2="12" y1="12" x2="19" x1="5"></line></svg></span>
     </button>
</form>

{% endblock principal %}

templates/entidad/nueva-localidad.html
{% extends "base.html" %}
{% load static  %}

{% block titulo_principal %}
    My Veterinaria | Nuevo Localidad
{% endblock %}


{% block principal %}

<form method="POST" class="form-group">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="button-submit">
        <span class="button__text">Crear</span>
        <span class="button__icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" viewBox="0 0 24 24" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" stroke="currentColor" height="24" fill="none" class="svg"><line y2="19" y1="5" x2="12" x1="12"></line><line y2="12" y1="12" x2="19" x1="5"></line></svg></span>
     </button>
</form>

{% endblock principal %}

templates/entidad/register.html
{% extends "base.html" %}

{% block principal %}
    <h2>Create your account!</h2>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn">Sign up</button>
    </form>
{% endblock principal %}